// @ts-check
//
// Docusaurus config for the standalone epsil.dev site.
//
// This is a second build of the *same* repo, not a second repo: it shares
// `src/components`, `src/theme` (notably the swizzled CodeBlock that renders
// Epsil syntax highlighting), `src/css` and `static/`. What it does not share
// is content — it serves only `docs/epsil`, rooted at `/`, with its own
// sidebar, navigation and landing page.
//
//   npx docusaurus start --config docusaurus.epsil.config.ts --port 3001
//   npx docusaurus build --config docusaurus.epsil.config.ts --out-dir build-epsil
//
// `docs/epsil/*.md` is generated by `scripts/sync-epsil-docs.mjs`, which strips
// the `/epsil` prefix the upstream authors write into slugs and internal links.
// Run it (or `npm run build`) before starting the dev server on a fresh clone.

import styles from './src/prism/theme-light';
import loadScripts from './plugins/load-scripts';
import llmsTxt from './plugins/llms-txt';
import remarkMath from 'remark-math';

import codePlaygroundRemarkPlugin from './plugins/code-playground';
import epsilPlaygroundRemarkPlugin from './plugins/epsil-playground';
import remarkLatexDelimiters from './plugins/remark-latex-delimiters';
import {
  getDocusaurusNavbarConfig,
  getDocusaurusFooterConfig,
} from './src/shared/utils/docusaurus-config';
import epsilNavigation from './src/shared/config/navigation-epsil.json';

import type { Config } from '@docusaurus/types';

const remarkPlugins = [
  codePlaygroundRemarkPlugin,
  epsilPlaygroundRemarkPlugin,
  remarkLatexDelimiters,
  remarkMath,
];

/** @type {import('@docusaurus/types').Config} */
const config: Config = {
  title: 'Epsil',
  titleDelimiter: '·',
  tagline: 'A programming language for scientific computing',
  favicon: '/img/logo.webp',

  url: 'https://epsil.dev',
  baseUrl: '/',
  trailingSlash: true,

  // Cloudflare Pages, not GitHub Pages: there is no CNAME file and no
  // deployment branch. `scripts/deploy-epsil.sh` uploads `build-epsil/`
  // directly with wrangler.
  organizationName: 'cortex-js',
  projectName: 'epsil.dev',

  // This site builds clean — zero broken links, zero broken anchors — so these
  // throw to keep it that way. mathlive.io still has a backlog of ~80 broken
  // anchors and stays on 'warn' until that is cleared; the ratchet only works
  // from zero.
  onBrokenLinks: 'throw',
  onBrokenAnchors: 'throw',
  onDuplicateRoutes: 'throw',

  markdown: {
    hooks: {
      onBrokenMarkdownLinks: 'warn',
    },
  },

  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
  },

  // `static/` carries the fonts, icons.svg and images the shared components
  // reference; `static-epsil/` adds the Cloudflare Pages `_headers`/`_redirects`
  // and anything specific to this site.
  staticDirectories: ['static', 'static-epsil'],

  presets: [
    [
      'classic',
      /** @type {import('@docusaurus/preset-classic').Options} */
      {
        sitemap: {
          changefreq: 'weekly',
          priority: 0.5,
          ignorePatterns: ['/tags/**'],
          filename: 'sitemap.xml',
        },

        docs: {
          path: 'docs/epsil',
          routeBasePath: '/',
          sidebarPath: './sidebars.epsil.js',
          showLastUpdateTime: true,
          remarkPlugins,
        },

        // The mathlive.io homepage lives in `src/pages`; this site has its own.
        pages: {
          path: 'src/pages-epsil',
          remarkPlugins,
        },

        blog: false,

        theme: {
          customCss: [
            './src/shared/styles/variables.css',
            './src/css/colors.css',
            './src/css/typography.css',
            './src/css/code-playground.css',
            './src/css/tables.css',
            './src/css/custom.css',
            './src/css/code.css',
            './src/css/icons.css',
          ],
        },
      },
    ],
  ],

  // The Inter font is hosted on rsms.me
  headTags: [
    {
      tagName: 'link',
      attributes: { rel: 'preconnect', href: 'https://rsms.me/' },
    },
    {
      tagName: 'link',
      attributes: {
        rel: 'stylesheet',
        href: 'https://rsms.me/inter/inter.css',
        media: 'print',
        onload: "this.media='all'",
      },
    },
    {
      tagName: 'link',
      attributes: {
        rel: 'preload',
        as: 'font',
        type: 'font/woff2',
        href: '/fonts/berkeley-mono/BerkeleyMono-Regular.woff2',
        crossorigin: 'anonymous',
      },
    },
    {
      tagName: 'link',
      attributes: {
        rel: 'preload',
        as: 'font',
        type: 'font/woff2',
        href: '/fonts/berkeley-mono/BerkeleyMono-Bold.woff2',
        crossorigin: 'anonymous',
      },
    },
  ],

  // Several Epsil pages use `$…$` math, rendered by MathLive after each route
  // change — same mechanism as mathlive.io.
  clientModules: ['./modules/route-update.js'],

  plugins: [
    loadScripts,
    [
      llmsTxt,
      {
        summary:
          'Documentation for Epsil, a programming language for scientific computing built on the Compute Engine.',
        // A single-product site: one bundle with every page is more useful to
        // an agent than three per-section ones, and `scripts/build.sh` copies
        // it to the legacy kb-epsil.md / llms-cortex.txt names on mathlive.io.
        fullBundle: 'llms-full.txt',
      },
    ],
  ],

  // Search. mathlive.io uses Algolia DocSearch (see `docusaurus.config.ts`),
  // whose `cortexjs` index crawls mathlive.io only and holds no epsil.dev URLs.
  // Rather than commission a second crawler, this site indexes itself at build
  // time: `docs/epsil` is 23 pages / ~230KB of markdown, small enough that the
  // whole lunr index ships to the browser and search runs with no network
  // round-trip and no service to keep in sync with the deploy.
  themes: [
    [
      '@easyops-cn/docusaurus-search-local',
      /** @type {import('@easyops-cn/docusaurus-search-local').PluginOptions} */
      ({
        // Docs are rooted at `/` here, so this has to match `routeBasePath`
        // above. The landing page in `src/pages-epsil/` is still left out:
        // it is not a doc permalink, and `indexPages` stays at its default.
        docsRouteBasePath: '/',
        // Only used to compute the content hash the index filename carries.
        docsDir: 'docs/epsil',
        indexBlog: false,

        // This documents a programming language whose keywords are English
        // stop words — `if`, `for`, `in`, `do`, `then`, `not`, `and`, `or`.
        // Filtering those out would make them unsearchable.
        removeDefaultStopWordFilter: true,

        // Hash in the filename, not a query string, so `_headers` can cache
        // the index immutably in `static-epsil/_headers`.
        hashed: 'filename',

        // No typo tolerance. The default edit distance of 1 is actively
        // harmful on this corpus: `match` — a keyword — is one edit from
        // `math`, `watch` and `catch`, and this is a site about math, so the
        // false positives outnumber the rescued typos.
        fuzzyMatchingDistance: 0,

        highlightSearchTermsOnTargetPage: true,
        explicitSearchResultPath: true,
      }),
    ],
  ],

  themeConfig:
    /** @type {import('@docusaurus/preset-classic').ThemeConfig} */
    {
      image: 'img/social-card.jpg',
      colorMode: {
        disableSwitch: true,
        respectPrefersColorScheme: true,
      },

      docs: {
        sidebar: {
          hideable: true,
          autoCollapseCategories: false,
        },
      },

      // No `algolia` block: search is served by the local index declared in
      // `themes` above, not by DocSearch.

      navbar: getDocusaurusNavbarConfig(epsilNavigation),
      footer: getDocusaurusFooterConfig(epsilNavigation),
      prism: {
        additionalLanguages: [
          'markup',
          'css',
          'javascript',
          'typescript',
          'json',
          'latex',
          'bash',
        ],
        theme: styles,
      },
    },
};

export default config;
