// Redirect the Epsil documentation's former mathlive.io homes to epsil.dev.
//
// The language docs used to be a section of this site, first at /cortex/ and
// then at /epsil/. They now have their own site, so the docs plugin no longer
// builds them here (`docs.exclude` in docusaurus.config.ts) and those routes
// would 404.
//
// mathlive.io is served by GitHub Pages, which cannot issue a real 301, so
// each old URL gets a stub page: a canonical link (so search engines transfer
// the URL), a meta refresh (so a browser with JS disabled still moves), and a
// location.replace (so the entry is not left in the back-button history).
//
// The route table is generated by `scripts/sync-epsil-docs.mjs`, which is the
// only place that sees each page's URL both before and after the move.

import fs from "node:fs/promises";
import path from "node:path";

function stubHtml(target, siteTitle) {
  const escaped = target.replace(/&/g, "&amp;").replace(/"/g, "&quot;");
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Redirecting to ${escaped}</title>
<link rel="canonical" href="${escaped}">
<meta name="robots" content="noindex">
<meta http-equiv="refresh" content="0; url=${escaped}">
<script>window.location.replace("${escaped}");</script>
</head>
<body>
<p>The Epsil documentation has moved to <a href="${escaped}">${escaped}</a>.</p>
<p><a href="/">Back to ${siteTitle}</a></p>
</body>
</html>
`;
}

/**
 * @param {import('@docusaurus/types').LoadContext} context
 * @param {{redirects: {target: string, routes: Record<string, string>}, alsoUnder?: string[]}} options
 */
export default function epsilRedirectPlugin(context, options = {}) {
  const { siteConfig } = context;
  const { redirects, alsoUnder = [] } = options;

  return {
    name: "epsil-redirect",

    async postBuild({ outDir }) {
      if (!redirects?.routes) {
        console.warn("[epsil-redirect] No route table supplied; nothing emitted");
        return;
      }

      const { target, routes } = redirects;
      let count = 0;

      for (const [from, to] of Object.entries(routes)) {
        const destination = new URL(to, target).href;

        // The canonical old path, plus any earlier alias of the same section
        // (/cortex/… before the rename). Writing those here rather than
        // leaving them to plugin-client-redirects avoids a double hop:
        // /cortex/syntax/ -> /epsil/syntax/ -> epsil.dev/syntax/.
        const paths = [from, ...alsoUnder.map((prefix) => from.replace(/^\/epsil/, prefix))];

        for (const p of new Set(paths)) {
          const file = path.join(outDir, p, "index.html");
          await fs.mkdir(path.dirname(file), { recursive: true });
          await fs.writeFile(file, stubHtml(destination, siteConfig.title), "utf8");
          count++;
        }
      }

      console.log(`[epsil-redirect] ${count} redirect stubs -> ${target}`);
    },
  };
}
