#!/bin/bash

set -e  # exit immediately on error

cd "$(dirname "$0")/.."

echo "Building started at" `date "+%H:%M:%S"`

# GC customizations
export RUBY_GC_MALLOC_LIMIT=79000000
export RUBY_HEAP_MIN_SLOTS=800000
export RUBY_HEAP_FREE_MIN=100000
export RUBY_HEAP_SLOTS_INCREMENT=400000
export RUBY_HEAP_SLOTS_GROWTH_FACTOR=1

# make build

## Preprocess
## Typedoc doesn't handle optional parameters in JSDOC, so strip them
## See https://github.com/TypeStrong/typedoc/issues/567

# **NOTE**: the .d.ts file is modified in place. Would be better to use pipelining
# or perhaps the <() bash operator.

sed -i node_modules/mathlive/dist/mathlive.d.ts -E -e 's/@param(.*)\[([^=]+)=(.+)\]/@param\1\2/g'   
sed -i node_modules/mathlive/dist/mathlive.d.ts -E -e 's/@param(.*)\[(.+)\]/@param\1\2/g'   

## Typedoc (.d.ts -> .json)
npx typedoc --mode modules --includeDeclarations --excludeExternals --excludePrivate --excludeProtected --hideGenerator --readme none --json _data/mathfield.json node_modules/mathlive/dist/mathlive.d.ts

## Makedoc (.json -> .md)
./script/makedoc _data/mathfield.json

## Build (.md -> .html)
bundle exec jekyll build
