#!/bin/bash

set -e  # exit immediately on error
set -o nounset   # abort on unbound variable
set -o pipefail  # don't hide errors within pipes
# set -x    # for debuging, trace what is being executed.

cd "$(dirname "$0")/.."

tput sc # save cursor

echo "Cleaning..."

rm -rf "./_site"
rm -rf "./.jekyll-cache"
rm -rf "./docs"

tput rc;tput el # rc = restore cursor, el = erase to end of line

echo "Cleaned."