#!/bin/sh

set -e  # exit immediately on error

cd "$(dirname "$0")/.."

# Get the latest submodule (submodules/cortex-js.github.io)
git submodule sync --recursive
git submodule update --init --recursive

# Make a build

./script/build
./script/test

# Add the .nojekyll file to prevent GH Pages from processing the content
touch submodules/cortex-js.github.io/.nojekyll

# Add CNAME file
printf "cortexjs.io" >submodules/cortex-js.github.io/CNAME

