#!/bin/bash

set -e  # exit immediately on error
set -o nounset   # abort on unbound variable
set -o pipefail  # don't hide errors within pipes
# set -x    # for debuging, trace what is being executed.

cd "$(dirname "$0")/.."

# Remove the CNAME file, which is used
# to indicate if this is a production or development build
[ -f "./submodules/cortex-js.github.io/CNAME" ] && rm "./submodules/cortex-js.github.io/CNAME"

## Preprocess

# Typedoc doesn't handle optional parameters in JSDOC, so strip them
# See https://github.com/TypeStrong/typedoc/issues/567

sed -E -e 's/@param(.*)\[([^=]+)=(.+)\]/@param\1\2/g' \
    node_modules/mathlive/dist/mathlive.d.ts | \
sed -E -e 's/@param(.*)\[(.+)\]/@param\1\2/g' > \
    node_modules/mathlive/dist/mathlive.proc.d.ts 

## Typedoc (.d.ts -> .json)
npx typedoc --mode modules \
    --includeDeclarations \
    --excludeExternals \
    --excludePrivate \
    --excludeProtected \
    --hideGenerator \
    --readme none \
    --json _data/mathfield.json \
    node_modules/mathlive/dist/mathlive.proc.d.ts

## Makedoc (.json -> .md)
./scripts/makedoc _data/mathfield.json

## Build (.md -> .html)
bundle exec jekyll build -q
