#!/bin/bash

set -e  # exit immediately on error
set -o nounset   # abort on unbound variable
set -o pipefail  # don't hide errors within pipes
# set -x    # for debuging, trace what is being executed.

cd "$(dirname "$0")/.."

# Get the latest submodule (_site)
git submodule sync --recursive
git submodule update --init --recursive

# Make a build

./scripts/build
./scripts/test

# Add the .nojekyll file to prevent GH Pages from processing the content
touch _site/.nojekyll

# Add CNAME file
echo "cortexjs.io" >_site/CNAME

